apiVersion: apps/v1
kind: Deployment
metadata:
  name: ee-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ee-prometheus
  template:
    metadata:
      labels:
        app: ee-prometheus
    spec:
      containers:
        - name: ee-prometheus
          image: registry/app:tag
          ports:
            - containerPort: 9090
          resources:
            limits:
              cpu: 300m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 100Mi
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9090
            initialDelaySeconds: 20
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /-/healthy
              port: 9090
            initialDelaySeconds: 20
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
