apiVersion: v1
kind: Service
metadata:
  name: ee-prometheus
spec:
  type: ClusterIP
  ports:
    - port: 9090
      name: metrics
      targetPort: 9090
      protocol: TCP
  selector:
    app: ee-prometheus
