apiVersion: apps/v1
kind: Deployment
metadata:
  name: ee-qdrant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ee-qdrant
  template:
    metadata:
      labels:
        app: ee-qdrant
    spec:
      containers:
        - name: ee-qdrant
          image: registry/app:tag
          ports:
            - containerPort: 6333
          volumeMounts:
            - name: qdrant-storage
              mountPath: /qdrant/storage
          resources:
            limits:
              cpu: 300m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 100Mi
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /healthz
              port: 6333
            initialDelaySeconds: 20
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 6333
            initialDelaySeconds: 20
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: qdrant-storage
          persistentVolumeClaim:
            claimName: ee-qdrant-pvc
