# fly.toml app configuration file generated for ee-qdrant on 2023-07-02T17:57:05+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ee-qdrant"
primary_region = "ams"

[[mounts]]
  source = "qd_data"
  destination = "/qdrant/storage"

[[services]]
  protocol = "tcp"
  internal_port = 6333
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 3

  [[services.ports]]
    port = 6333
    handlers = ["http"]

  [[services.tcp_checks]]
    interval = "15s"
    grace_period = "10s"
    restart_limit = 0

[[services]]
  protocol = "tcp"
  internal_port = 6334

  [[services.ports]]
    port = 6334
    [services.ports.tls_options]
      alpn = ["h2"]

  [[services.tcp_checks]]
    interval = "15s"
    grace_period = "10s"
    restart_limit = 0

[metrics]
  port = 6333
  path = "/metrics"
