debug: true
log_level: INFO

service:
  host: 0.0.0.0
  http_port: 6333
  grpc_port: 6334
  enable_cors: true
  enable_tls: false

# TLS configuration.
# Required if either service.enable_tls is true.
#tls:
# Server certificate chain file
#cert: ./tls/cert.pem
# Server private key file
#key: ./tls/key.pem
#cert_ttl: 3600
