version: "3.8"
name: adm-stack
services:
  web:
    image: adm-frontend
    container_name: adm-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    depends_on:
      - db
    ports:
      - "8080:3000"
