# Dockerfile for ASA Database

# Create Postgres
FROM postgres:15.3-alpine AS deploy-db
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_USER=postgres
ENV POSTGRES_DB=asa-local-db

# Create pgAdmin
FROM dpage/pgadmin4:7.1 AS deploy-db-pgadmin
ENV PGADMIN_DEFAULT_EMAIL="admin@admin.com"
ENV PGADMIN_DEFAULT_PASSWORD="root"