version: "3.8"
name: ee-application
services:
  ee-pocketbase:
    image: ee-pocketbase
    container_name: ee-pocketbase
    restart: unless-stopped
    build:
      context: ./pocketbase
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    volumes:
      - ./pocketbase/pb_data:/pb_data
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
