document_topics = [
    "Technology", "Software", "Hardware", "Network", "Cybersecurity", 
    "Artificial Intelligence", "Blockchain", "Science", "Biology", "Chemistry", 
    "Physics", "Astronomy", "Environmental", "Health", "Nutrition", 
    "Mental Health", "Medicine", "Fitness", "Disease", "Finance", 
    "Investment", "Banking", "Insurance", "Cryptocurrency", "Stock Market", 
    "Business", "Entrepreneurship", "Marketing", "E-commerce", "Human Resources", 
    "Strategy", "Education", "Online Learning", "Curriculum", "College", 
    "K-12", "Scholarship", "Legal", "Contract", "Intellectual Property", 
    "Criminal", "Employment Law", "Real Estate", "Art and Culture", "Music", 
    "Literature", "Film", "Theatre", "Visual Arts", "Politics", 
    "Government", "Policy", "Elections", "International Relations", "Activism", 
    "Environment", "Sustainability", "Climate Change", "Conservation", "Renewable Energy", 
    "Pollution", "Sports", "Football", "Basketball", "Baseball", 
    "Soccer", "Olympics", "Travel", "Adventure", "Hotels", 
    "Flights", "Tourism", "Cuisine", "Social Media", "Platforms", 
    "Trends", "Influencers", "Digital Marketing", "Analytics", "Automotive", 
    "Electric Vehicles", "Cars", "Trucks", "Motorcycles", "Auto Industry", 
    "Real Estate", "Residential", "Commercial", "Mortgages", "Investment", 
    "Architecture", "Lifestyle", "Fashion", "Food and Drink", "Wellness", 
    "Hobbies", "Relationships", "Religion", "Christianity", "Islam", 
    "Hinduism", "Buddhism", "Spirituality", "Entertainment", "Movies", 
    "Television", "Gaming", "Books", "Celebrity", "Construction", 
    "Architecture", "Engineering", "Infrastructure", "Materials", "Project Management", 
    "Manufacturing", "Production", "Robotics", "Supply Chain", "Quality Control", 
    "Logistics", "Agriculture", "Farming", "Livestock", "Horticulture", 
    "Organic", "Sustainability"
]
