# fly.toml app configuration file generated for ee-backend on 2023-06-14T21:04:29+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ee-backend"
primary_region = "ams"

[http_service]
  internal_port = 5003
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
