name: PocketBase Docker CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push
        run: |
          docker build -t botwayorg/pb-core:latest --file Dockerfile.core .
          docker push botwayorg/pb-core:latest

          docker build -t botwayorg/pocketbase:latest .
          docker push botwayorg/pocketbase:latest
