apiVersion: v1
kind: Service
metadata:
  name: ee-pocketbase
spec:
  type: ClusterIP
  ports:
    - port: 8090
      name: api
      targetPort: 8090
      protocol: TCP
  selector:
    app: ee-pocketbase
