# fly.toml app configuration file generated for ee-pocketbase on 2023-06-14T20:50:38+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ee-pocketbase"
primary_region = "fra"

[[mounts]]
  source = "pb_data"
  destination = "/pb/pb_data"

[http_service]
  internal_port = 8090
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
