name: Deploy Development

on:
  workflow_run:
    workflows: ["Frontend Tests", "Backend Tests"]
    types:
      - completed

jobs:
  deploy-frontend-test:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.pull_request.base.ref == 'main' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: cd frontend && flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_FRONTEND }}
