name: Pocektbase

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-pocketbase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: cd pocketbase && flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_POCKETBASE }}
