name: Pocketbase

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Fly CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "/home/runner/.fly/bin" >> $GITHUB_PATH

      - name: Login to Fly.io
        run: flyctl auth login -t ${{ secrets.FLY_API_TOKEN_POCKETBASE }}

      - name: Deploy to Fly.io
        run: |
          cd pocketbase
          flyctl deploy
