name: Qdrant

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-qdrant:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: cd qdrant && flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_QDRANT }}
